"""Initial schema: sessions, conversations, cached_answers

Revision ID: 9d127d350d71
Revises:
Create Date: 2025-12-29 10:57:06.207274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d127d350d71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('tfidf_vector', sa.Text(), nullable=False),
    sa.Column('variations', sa.JSON(), nullable=False),
    sa.Column('variation_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cached_answers_last_used', 'cached_answers', [sa.literal_column('last_used DESC')], unique=False)
    op.create_index(op.f('ix_cached_answers_question'), 'cached_answers', ['question'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_session_id'), 'session', ['session_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('evaluator_used', sa.Boolean(), nullable=False),
    sa.Column('evaluator_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.create_index('ix_conversations_timestamp_desc', 'conversations', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_timestamp_desc', table_name='conversations')
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_session_session_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_cached_answers_question'), table_name='cached_answers')
    op.drop_index('ix_cached_answers_last_used', table_name='cached_answers')
    op.drop_table('cached_answers')
    # ### end Alembic commands ###
